apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: creometry-backend
  template:
    metadata:
      labels:
        run: creometry-backend
    spec:
      volumes:
        # need to create this configmap for the backend to use
        #  kubectl create configmap app.config --from-file=.env
        - name: config-volume
          configMap:
            name: app.config
      containers:
        - image: creometry/backend
          name: backend
          volumeMounts:
            - mountPath: /app/config
              name: config-volume
          ports:
            - containerPort: 3001
          resources:
            limits:
              cpu: "100m"
              memory: "256Mi"
            requests:
              cpu: "5m"
              memory: "10Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: creometry-backend-svc
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
  selector:
    run: creometry-backend
