# create the config map for the backend to use from a .env file
# kubectl create configmap go-provisioner-env -n go-provisioner-ns --from-file=.env

apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-provisioner-deploy
  # namespace: go-provisioner-ns
spec:
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      run: go-provisioner
  template:
    metadata:
      labels:
        run: go-provisioner
    spec:
      containers:
        - image: creometry/go-provisioner:v0.0.1
          name: go-provisioner
          ports:
            - containerPort: 3001
          resources:
            limits:
              cpu: "100m"
              memory: "256Mi"
            requests:
              cpu: "5m"
              memory: "10Mi"
          volumeMounts:
            - name: go-provisioner-config-volume
              mountPath: "/app/config"
              readOnly: true
            - name: go-provisioner-secrets-volume
              mountPath: "/app/secrets"
              readOnly: true
      volumes:
        - name: go-provisioner-config-volume
          configMap:
            name: go-provisioner-config
        - name: go-provisioner-secrets-volume
          secret:
            secretName: go-provisioner-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: go-provisioner-svc
  # namespace: go-provisioner-ns
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
  selector:
    run: go-provisioner
---
apiVersion: v1
data:
  # RANCHER_TOKEN: add rancher token to a secret
  CLUSTER_ID: c-zb22d
  RANCHER_URL: https://tn.cloud.creometry.com
  PAYMEE_URL: https://sandbox.paymee.tn
  # PAYMEE_TOKEN: add rancher token to a secret
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: go-provisioner-config
#  namespace: go-provisioner-ns
