
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-service-deploy
 # namespace: resources-service-ns
spec:
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      run: resources-service
  template:
    metadata:
      labels:
        run: resources-service
    spec:
      automountServiceAccountToken: true
      containers:
        - image: seifbarouni/resources-service:latest
          name: resources-service
          ports:
            - containerPort: 3002
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "5m"
              memory: "10Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: resources-service-svc
 # namespace: resources-service-ns
spec:
  ports:
    - name: "3002"
      port: 3002
      targetPort: 3002
  selector:
    run: resources-service
