name: go-provisioner CI

on:
  push:
    branches:
      - "**"

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.18

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: creometry/go-provisioner
          tags: v0.0.1
          dockerfile: go-provisioner/Dockerfile
          registry: docker.io
          directory: go-provisioner
          username: creometry
          password: ${{ secrets.dashboard }}
